apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-config
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "Cloudnative-pg Cluster",
           "Group": "Servers",
           "Port": 5432,
           "Username": "app",
           "Host": "cluster-rw",
           "SSLMode": "prefer",
           "MaintenanceDB": "app"
         }
       }
   }
