apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.9.4
  name: redpanda-config-watcher
  namespace: redpanda
stringData:
  sasl-user.sh: |-
    #!/usr/bin/env bash

    trap 'error_handler $? $LINENO' ERR

    error_handler() {
      echo "Error: ($1) occurred at line $2"
    }

    set -e

    # rpk cluster health can exit non-zero if it's unable to dial brokers. This
    # can happen for many reasons but we never want this script to crash as it
    # would take down yet another broker and make a bad situation worse.
    # Instead, just wait for the command to eventually exit zero.
    echo "Waiting for cluster to be ready"
    until rpk cluster health --watch --exit-when-healthy; do
      echo "rpk cluster health failed. Waiting 5 seconds before trying again..."
      sleep 5
    done
    echo "Nothing to do. Sleeping..."
    sleep infinity
type: Opaque
