apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.9.4
  name: redpanda-test-lifecycle
  namespace: redpanda
spec:
  containers:
  - command:
    - /bin/timeout
    - "180"
    - bash
    - -xec
    - |
      /bin/timeout -v 45 bash -x /var/lifecycle/preStop.sh
      ls -l /tmp/preStop*
      test -f /tmp/preStopHookStarted
      test -f /tmp/preStopHookFinished

      /bin/timeout -v 45 bash -x /var/lifecycle/postStart.sh
      ls -l /tmp/postStart*
      test -f /tmp/postStartHookStarted
      test -f /tmp/postStartHookFinished
    env:
    - name: SERVICE_NAME
      value: redpanda-0
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    name: redpanda
    securityContext:
      allowPrivilegeEscalation: null
      runAsGroup: 101
      runAsNonRoot: null
      runAsUser: 101
    volumeMounts:
    - mountPath: /etc/redpanda
      name: config
    - mountPath: /var/lifecycle
      name: lifecycle-scripts
  restartPolicy: Never
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
  volumes:
  - configMap:
      name: redpanda
    name: config
  - name: lifecycle-scripts
    secret:
      defaultMode: 509
      secretName: redpanda-sts-lifecycle
