apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.9.4
  name: redpanda
  namespace: redpanda
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: redpanda-statefulset
      app.kubernetes.io/instance: redpanda
      app.kubernetes.io/name: redpanda
  serviceName: redpanda
  template:
    metadata:
      annotations:
        config.redpanda.com/checksum: f482ef08acdb474332abcf5f39640facdcc4c78e41f6d0f01ec694d7bdcb620d
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda-statefulset
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: redpanda
        helm.sh/chart: redpanda-5.9.4
        redpanda.com/poddisruptionbudget: redpanda
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: redpanda-statefulset
                app.kubernetes.io/instance: redpanda
                app.kubernetes.io/name: redpanda
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - rpk
        - redpanda
        - start
        - --advertise-rpc-addr=$(SERVICE_NAME).redpanda.redpanda.svc.cluster.local.:33145
        env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                timeout -v 45 bash -x /var/lifecycle/postStart.sh
                true
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                timeout -v 45 bash -x /var/lifecycle/preStop.sh
                true # do not fail and cause the pod to terminate
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl --silent --fail -k -m 5  "http://${SERVICE_NAME}.redpanda.redpanda.svc.cluster.local.:9644/v1/status/ready"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
        name: redpanda
        ports:
        - containerPort: 9644
          name: admin
        - containerPort: 9645
          name: admin-default
        - containerPort: 8082
          name: http
        - containerPort: 8083
          name: http-default
        - containerPort: 9093
          name: kafka
        - containerPort: 9094
          name: kafka-default
        - containerPort: 33145
          name: rpc
        - containerPort: 8081
          name: schemaregistry
        - containerPort: 8084
          name: schema-default
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              set -x
              RESULT=$(rpk cluster health)
              echo $RESULT
              echo $RESULT | grep 'Healthy:.*true'
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 0
        resources:
          limits:
            cpu: 1
            memory: 2.5Gi
          requests:
            cpu: 1
            memory: 2.5Gi
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              set -e
              RESULT=$(curl --silent --fail -k -m 5  "http://${SERVICE_NAME}.redpanda.redpanda.svc.cluster.local.:9644/v1/status/ready")
              echo $RESULT
              echo $RESULT | grep ready
          failureThreshold: 120
          initialDelaySeconds: 1
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/redpanda
          name: config
        - mountPath: /tmp/base-config
          name: redpanda
        - mountPath: /var/lifecycle
          name: lifecycle-scripts
        - mountPath: /var/lib/redpanda/data
          name: datadir
      - args:
        - -c
        - trap "exit 0" TERM; exec /etc/secrets/config-watcher/scripts/sasl-user.sh
          & wait $!
        command:
        - /bin/sh
        env: []
        image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
        name: config-watcher
        resources: {}
        securityContext: {}
        volumeMounts:
        - mountPath: /etc/redpanda
          name: config
        - mountPath: /etc/secrets/config-watcher/scripts
          name: redpanda-config-watcher
      imagePullSecrets: null
      initContainers:
      - command:
        - /bin/bash
        - -c
        - rpk redpanda tune all
        image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
        name: tuning
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_RESOURCE
          privileged: true
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/redpanda
          name: redpanda
      - command:
        - /bin/bash
        - -c
        - trap "exit 0" TERM; exec $CONFIGURATOR_SCRIPT "${SERVICE_NAME}" "${KUBERNETES_NODE_NAME}"
          & wait $!
        env:
        - name: CONFIGURATOR_SCRIPT
          value: /etc/secrets/configurator/scripts/configurator.sh
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef: null
            fieldRef:
              fieldPath: metadata.name
            resourceFieldRef: null
            secretKeyRef: null
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
        name: redpanda-configurator
        resources: {}
        securityContext:
          allowPrivilegeEscalation: null
          runAsGroup: 101
          runAsNonRoot: null
          runAsUser: 101
        volumeMounts:
        - mountPath: /etc/redpanda
          name: config
        - mountPath: /tmp/base-config
          name: redpanda
        - mountPath: /etc/secrets/configurator/scripts/
          name: redpanda-configurator
      nodeSelector: {}
      priorityClassName: ""
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: default
      terminationGracePeriodSeconds: 90
      tolerations: []
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: redpanda-statefulset
            app.kubernetes.io/instance: redpanda
            app.kubernetes.io/name: redpanda
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - name: lifecycle-scripts
        secret:
          defaultMode: 509
          secretName: redpanda-sts-lifecycle
      - configMap:
          name: redpanda
        name: redpanda
      - emptyDir: {}
        name: config
      - name: redpanda-configurator
        secret:
          defaultMode: 509
          secretName: redpanda-configurator
      - name: redpanda-config-watcher
        secret:
          defaultMode: 509
          secretName: redpanda-config-watcher
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations: null
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/name: redpanda
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    status: {}
