apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.9.4
  name: redpanda-test-console
  namespace: redpanda
spec:
  containers:
  - command:
    - /usr/bin/timeout
    - "120"
    - bash
    - -c
    - |
      curl  -svm3 --fail --retry "120" --retry-max-time "120" --retry-all-errors -o - -w "\nstatus=%{http_code} %{redirect_url} size=%{size_download} time=%{time_total} content-type=\"%{content_type}\"\n"  http://redpanda-console.redpanda.svc:8080/api/cluster
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    name: redpanda
    securityContext:
      allowPrivilegeEscalation: null
      runAsGroup: 101
      runAsNonRoot: null
      runAsUser: 101
    volumeMounts:
    - mountPath: /etc/redpanda
      name: config
  restartPolicy: Never
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
  volumes:
  - configMap:
      name: redpanda
    name: config
