apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.9.4
  name: redpanda-test-kafka-produce-consume
  namespace: redpanda
spec:
  containers:
  - command:
    - /usr/bin/timeout
    - "120"
    - bash
    - -c
    - "set -e\nuntil rpk topic create produce.consume.test.$POD_NAME \n  do sleep
      2\ndone\necho \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\necho
      \"Pandas are awesome!\" | rpk topic produce produce.consume.test.$POD_NAME\nsleep
      2\nrpk topic consume produce.consume.test.$POD_NAME -n 1 | grep \"Pandas are
      awesome!\"\nrpk topic delete produce.consume.test.$POD_NAME\n"
    env:
    - name: REDPANDA_BROKERS
      value: redpanda.redpanda.svc.cluster.local:9093
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    name: redpanda
    resources: null
    securityContext:
      allowPrivilegeEscalation: null
      runAsGroup: 101
      runAsNonRoot: null
      runAsUser: 101
    volumeMounts:
    - mountPath: /etc/redpanda
      name: config
  restartPolicy: Never
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
  volumes:
  - configMap:
      name: redpanda
    name: config
