apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: console
    app.kubernetes.io/version: v2.7.0
    helm.sh/chart: console-0.7.29
  name: redpanda-console
  namespace: redpanda
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/name: console
  type: ClusterIP
