apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-5.9.4
  name: redpanda-post-upgrade
  namespace: redpanda
spec:
  backoffLimit: null
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: redpanda-post-upgrade
        app.kubernetes.io/instance: redpanda
        app.kubernetes.io/name: redpanda
      name: redpanda
    spec:
      affinity: {}
      containers:
      - args:
        - |
          set -e

          rpk cluster config set default_topic_replications 3
          rpk cluster config set storage_min_free_bytes 1073741824
          if [ -d "/etc/secrets/users/" ]; then
              IFS=":" read -r USER_NAME PASSWORD MECHANISM < <(grep "" $(find /etc/secrets/users/* -print))
              curl -svm3 --fail --retry "120" --retry-max-time "120" --retry-all-errors --ssl-reqd \
               \
              -X PUT -u ${USER_NAME}:${PASSWORD} \
              http://redpanda.redpanda.svc.cluster.local.:9644/v1/debug/restart_service?service=schema-registry || true
          fi
        command:
        - /bin/bash
        - -c
        env: []
        image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
        name: post-upgrade
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        volumeMounts:
        - mountPath: /etc/redpanda
          name: config
      imagePullSecrets: null
      nodeSelector: {}
      restartPolicy: Never
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: default
      tolerations: []
      volumes:
      - configMap:
          name: redpanda
        name: config
