version: '3.7'
services:
  keto:
    image: oryd/keto:v0.12.0-alpha.0
    ports:
      - "4466:4466"  # Read API
      - "4467:4467"  # Write API
    volumes:
      - type: bind
        source: ./keto.yml
        target: /home/ory/keto.yml